### ISSUE TITLE
hey please there's a problem while trying to start the app.py

### ISSUE THREAD

**Issue by TakuroX64** [ghrlt/spotify-status-to-instagram-notes#3]
![image](https://github.com/ghrlt/spotify-status-to-instagram-notes/assets/121630592/785eb537-ae35-403c-a21d-18e809140716)

I think this is a very useful program so please if anyone could give me some help
is it an instgram API update that made the code bug or something ?
thank you

**Comment by ghrlt** [comment]
What version of instagrapi are you on?
Anyway, I have a fix to do, I will check and update in coming days

**Comment by djokcho** [comment]
> What version of instagrapi are you on? Anyway, I have a fix to do, I will check and update in coming days

I have the same problem and I'm on the newest version, which version did you create the program with? @ghrlt

**Comment by ghrlt** [comment]
Hello, sorry for the reply delay.

Commit 8b12bad512f22c614040aedc5a7aeaa59f5ff3c7 should resolve any problem you had with [instagrapi](https://github.com/subzeroid/instagrapi) latest version
