### ISSUE TITLE
"Invalid access token. Unable to refresh it. Please re-authorize the app (delete spotify.session)."

### ISSUE THREAD

**Issue by GalaxyXYZ888** [ghrlt/spotify-status-to-instagram-notes#4]
After 1h. So what i think is the first time it refreshes, this appears. Why ? xd Shouldnt the refresh token handle the refresh of the access token ? 
"Invalid access token. Unable to refresh it. Please re-authorize the app (delete spotify.session)."

Thank you in advance love the project !

**Comment by ghrlt** [comment]
Hello, it's been a while... Sorry for that.

This commit https://github.com/ghrlt/spotify-status-to-instagram-notes/commit/773a72961c976ec3fc7b8ad1f8697ebc44211f80 should have patched it
