### ISSUE TITLE
Can we share spotify realtime music to instagram notes?

### ISSUE THREAD

**Issue by ashwin3454** [ghrlt/spotify-status-to-instagram-notes#7]
.
.
This feature has found in my Instagram notes section. but not working now. can u please find a soluton with your program?
.
.

![Picsart_24-11-16_06-24-41-320](https://github.com/user-attachments/assets/3b027d93-084d-4e80-9042-c9b55206c430)

**Comment by Pluzdev** [comment]
Hello, 

We already talked about adding this feature in a previous issue, check [here](https://github.com/ghrlt/Spotify-status-to-instagram-notes/issues/2)

I still haven't found anything that lets you add notes containing music directly, and unfortunately I don't think it exists at the moment. 

If you find anything that can help don't hesitate to share it with us !

**Comment by ghrlt** [comment]
I didn't know Instagram was planning on such feature.
tbh, if they do properly implements that feature, this repo will be archived.

Meanwhile if anyone successfully reverse-engineered the music feature, please contact us!
